ENT.Base 			= "npc_vj_hlr1_"
ENT.Type 			= "ai"
ENT.PrintName 		= "Fat Assassin"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Half-Life Resurgence"