ENT.Base 			= "npc_vj_hlr1_nihilanth"
ENT.Type 			= "ai"
ENT.PrintName 		= "Adolf Hitler"
ENT.Author 			= "oteek"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Crack-Life Resurgence"